# Generated by Django 5.0.1 on 2024-01-18 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=90)),
                ('meta_description', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, verbose_name='Service Name')),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.AddField(
            model_name='category',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service'),
        ),
    ]
